### ISSUE TITLE
Required Unity version is 2020.1 alpha 17 or later. : (

### ISSUE THREAD

**Issue by MostHated** [Unity-Technologies/MeshApiExamples#1]
The newest version on the hub looks like its alpha 15. I tried to open it with that just to see. I didn't expect it would work considering it said the actual minimum is alpha 17, but, you know. Is there an ETA on when a17 might be available? This looks awesome and I would love to play around with it.

Thanks,
-MH

**Comment by aras-p** [comment]
Yes, when it says it needs alpha 17, it means it. It's not out yet, and I don't know when it will be (hopefully soon?).

**Comment by aras-p** [comment]
Alpha 17 is out now btw.

**Comment by MostHated** [comment]
Ah, very good. Thank you.
