### ISSUE TITLE
[Question] Dynamic output vertex count

### ISSUE THREAD

**Issue by hybridherbst** [Unity-Technologies/MeshApiExamples#2]
The examples are great, but for me its a bit unclear how to deal with changing output counts.
Say I want to split a mesh by a plane (and cut triangles while doing so), the output count would be dependant on that. How would that be handled with a job? Allocate a large enough output buffer (same size as input) and then "shrink" later once it's clear how many triangles/vertices actually are there?

**Comment by aras-p** [comment]
Yeah that would be my guess: allocate a large enough buffer, and then you can keep that large buffer, but setup submesh info to only contain some vertex range.
