### ISSUE TITLE
Crashed on Android build

### ISSUE THREAD

**Issue by FanEric** [Unity-Technologies/MeshApiExamples#3]
I removed the profiling codes, added one button to trigger the CreateMesh_MeshDataApi method, and build on Android with the LargeScene, when I clicked the button on my Pixel 2, nothing happened, and few seconds later, the app crashed. While things went well on editor. Can anybody tell me why this happened?

**Comment by aras-p** [comment]
No idea, a crash callstack from android log would be useful. Maybe it crashed in some completely unrelated place?
