### ISSUE TITLE
Mesh compute access branch: a working (public) alpha version supporting it?

### ISSUE THREAD

**Issue by oscarbg** [Unity-Technologies/MeshApiExamples#4]
seen on aras_p Twitter a while ago..
still no alpha supporting some testing?
also can't keep asking if new "mesh shaders" stage could enable even more performance from this simple sample even as I suspect may be even farther in the roadmap for Unity support.. seeing also really we have no Vulkan mesh shader cross vendor extension yet.. compared to recent Vulkan KHR raytracing support..
thanks..

**Comment by aras-p** [comment]
Mesh compute shader access is in 2021.2a19, out now.

I don't know whether there are plans to expose mesh shaders.
